version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-delivery
    restart: always
    environment:
      POSTGRES_USER: temoh
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: delivery
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./01_create_tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql
      - ./create_table_delivery.sql:/docker-entrypoint-initdb.d/create_table_delivery.sql
      - ../data:/data/csv
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: delivery
      MB_DB_PORT: 5432
      MB_DB_USER: temoh
      MB_DB_PASS: postgres
      MB_DB_HOST: postgres
    volumes:
      - metabase-data:/metabase-data

volumes:
  pgdata:
  metabase-data: